// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1VMVKFmGcUrl8WVGsbxLOBfUEbZOrlZ0',
    appId: '1:914451946370:web:c344c58e5680cd924dcd9b',
    messagingSenderId: '914451946370',
    projectId: 'arkyn-29edb',
    authDomain: 'arkyn-29edb.firebaseapp.com',
    storageBucket: 'arkyn-29edb.firebasestorage.app',
    measurementId: 'G-BGNVV6Z8QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSLhr-ztYTdGouAgS0K4f9K9pr2c_V7Pw',
    appId: '1:914451946370:android:c02fe4058e72b6ba4dcd9b',
    messagingSenderId: '914451946370',
    projectId: 'arkyn-29edb',
    storageBucket: 'arkyn-29edb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7LDQpH-a57U3OzuU0ZH6nasiBqsRAJLc',
    appId: '1:914451946370:ios:3475fe660c76e66d4dcd9b',
    messagingSenderId: '914451946370',
    projectId: 'arkyn-29edb',
    storageBucket: 'arkyn-29edb.firebasestorage.app',
    iosBundleId: 'com.example.arkyn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7LDQpH-a57U3OzuU0ZH6nasiBqsRAJLc',
    appId: '1:914451946370:ios:3475fe660c76e66d4dcd9b',
    messagingSenderId: '914451946370',
    projectId: 'arkyn-29edb',
    storageBucket: 'arkyn-29edb.firebasestorage.app',
    iosBundleId: 'com.example.arkyn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1VMVKFmGcUrl8WVGsbxLOBfUEbZOrlZ0',
    appId: '1:914451946370:web:8af3d0a9559675824dcd9b',
    messagingSenderId: '914451946370',
    projectId: 'arkyn-29edb',
    authDomain: 'arkyn-29edb.firebaseapp.com',
    storageBucket: 'arkyn-29edb.firebasestorage.app',
    measurementId: 'G-0XB18F4LT0',
  );
}
